apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wordpress
data:
  MYSQL_DATABASE: wordpress
  MYSQL_USER: dawid
  WORDPRESS_DB_HOST: mysql:3306
  MYSQL_PASSWORD: password
