apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        # image: makram89/demo-wp:latest
        image: wordpress:6.7.1-php8.3-apache
        resources:
          limits:
            memory: "3Gi"
            cpu: "2000m"
          requests:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: WORDPRESS_DB_PASSWORD  # MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-config 
              key: MYSQL_DATABASE
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: wordpress-config   
              key: MYSQL_USER
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wordpress-config   
              key: WORDPRESS_DB_HOST  
        ports:
        - containerPort: 80
          name: wordpress
        - containerPort: 443
          name: wordpress-ssl
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html/wp-content
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
