apiVersion: v1
kind: Service
metadata:
  name: php-1-app-service
  namespace: php-app  
spec:
  selector:
    app: php-1-app
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 80
  type: LoadBalancer 
