apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: wordpress
  labels:
    type: local
spec:
  storageClassName: mysql-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: wordpress
spec:
  storageClassName: mysql-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
