apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: react-app 
spec:
  selector:
    app: react-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer 
