apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
spec:
  ports:
  - port: 443
    targetPort: 443
    name: wordpress-ssl 
  - port: 8000
    targetPort: 80  
    name: wordpress-http
  selector:
    app: wordpress
  type: LoadBalancer 
